media:
 - name: brand
   label: 'Pasta de logo'
   input: static/images/brand
   output: /images/brand
   extensions: [ webp ]
   
 - name: slide
   label: 'Pasta de Carrosel'
   input: static/images/slide
   output: /images/slide
   extensions: [ webp ]
   
content:
  - name: announcementBar
    label: 'Barra de anúncio'
    type: file
    path: 'src/cms/announcement-bar.json'
    format: 'json'
    fields: 
      - name: announcementBar
        label: 'Barra de anúncio'
        list: true
        type: string

        # é um comentario
  - name: generalConfiguration
    label: 'Configuração Geral'
    type: file
    path: 'src/cms/general-configuration.json'
    format: 'json'
    fields: 
      - name: companyInformation
        label: 'Informações da empresa'
        type: object
        fields:
          - name: companyName
            label: 'Nome da empresa'
            required: true
            type: string
          - name: companyBrand
            label: 'logo da empresa'
            description: 'Envie imagem somente em formato de Webp'
            type: image
            options:
             media: brand
         
  - name: slideCarousel
    label: 'Banners'
    type: file
    path: 'src/cms/slide-carousel.json'
    format: 'json'
    fields: 
     - name: imagesSlides
       label: 'imagens'
       required: false
       list: true
       type: object
       fields:
         - name: images
           label: 'Imagem do slide'
           type: image
           options:
            media: slide
         