content:
  - name: AnnouncementBar
    label: 'Barra de anúncio'
    type: file
    path: 'src/cms/announcement-bar.json'
    format: 'json'
    fields: 
      - name: AnnouncementBar
        label: 'Barra de anúncio'
        list: true
        type: string
  - name: BrandLogo
    label: 'Logo'
    type: file
    path: 'src/cms/brand-logo.json'
    format: 'json'
    fields: 
      - name: text
        label: 'texto simples'
        type: string
      