content:
  - name: announcementBar
    label: 'Barra de anúncio'
    type: file
    path: 'src/cms/announcement-bar.json'
    format: 'json'
    fields: 
      - name: announcementBar
        label: 'Barra de anúncio'
        list: true
        type: string

        # é um comentario
  - name: generalConfiguration
    label: 'Configuração Geral'
    type: file
    path: 'src/cms/general-configuration.json'
    format: 'json'
    fields: 
      - name: companyInformation
        label: 'Informações da empresa'
        type: object
        fields:
          - name: companyName
            label: 'Nome da empresa'
            type: string
          - name: companyBrand
            label: 'logo dad empresa'
            type: image
         
      