media:
 - name: brand
   label: 'Pasta de logo'
   input: static/images/brand
   output: /images/brand
   extensions: [ webp ]
   
 - name: banners
   label: 'Pasta de Carrosel'
   input: static/images/banners
   output: /images/banners
   extensions: [ webp ]
   
content:
  - name: announcementBar
    label: 'Barra de anúncio'
    type: file
    path: 'src/cms/announcement-bar.json'
    format: 'json'
    fields: 
      - name: announcementBar
        label: 'Barra de anúncio'
        list: true
        type: string

        # configurações de empresa
  - name: generalConfiguration
    label: 'Configuração Geral'
    type: file
    path: 'src/cms/general-configuration.json'
    format: 'json'
    fields: 
      - name: companyInformation
        label: 'Informações da empresa'
        type: object
        fields:
          - name: companyName
            label: 'Nome da empresa'
            required: true
            type: string
          - name: descrition
            label: 'Descrição da sua empresa'
            description: 'ex: empresa voltada para beleza'
            required: true
            type: string
          - name: companyBrand
            label: 'logo da empresa'
            description: 'Envie imagem somente em formato de Webp'
            type: image
            options:
             media: brand
          - name: social
            label: 'redes sociais'
            type: object
            fields:
              - name: email
                label: 'Email da sua empresa'
                description: 'ex: diretoria@guilhermeferragens.com.br'
                type: string
              - name: phone
                label: 'telefone da sua empresa'
                description: 'ex (16) 98345-5065'
                type: string
              - name: whatsapp
                label: 'Whatsapp da sua empresa'
                description: "ex: (16) 98345-5065"
                type: string 
              - name: intagram
                label: 'Intragram da sua empresa'
                type: string
              - name: linkedin
                label: 'Linkedin da sua empresa'
                type: string
              - name: facebook
                label: 'facebook da sua empresa'
                type: string
              - name: youtube
                label: 'Youtube da sua empresa'
                type: string
          - name: adress
            label: 'endereço da sua empresa'
            type: object
            fields:
              - name: cidade
                label: 'cidade da empresa'
                description: 'ex: Ribeirão Preto'
                type: string
              - name: cep
                label: 'cep da sua empresa'
                description: 'ex: 14020-078'
                type: string
              - name: rua
                label: 'nome da rua'
                description: 'ex: Travessa Macau'
                type: string
              - name: numero
                label: 'Numero da sua empresa'
                description: 'ex: 275'
                type: number
              - name: bairo
                label: 'nome do bairro da sua empresa'
                description: 'ex: Vila Seixas'
                type: string
               
        
  - name: banners
    label: 'Banners'
    type: file
    path: 'src/cms/banners.json'
    format: 'json'
    fields:
     - name: banners
       label: 'Selecione a imagem'
       type: object
       list: true
       fields:
        - name: link
          label: 'Link de redirecionamento'
          description: 'Ex: https://www.google.com'
          type: string
          required: false
        - name: blank
          label: 'Abrir em nova aba?'
          description: 'se ativo, abre o link em nova aba'
          type: boolean
          default: false
          required: false
        - name: desktopImage
          label: 'Imagem para Desktop'
          type: object
          fields:
            - name: src
              label: 'Selecione a imagem'
              description: 'Tamanho recomendado 3072x900 em .jpg, .jpeg, .webp ou .avif'
              type: image
              required: true
              options:
               media: banners
            - name: alt
              label: 'Descrição do Banner'
              description: 'Forneça um texto alternativo que descreva o conteúdo da imagem'
              type: string
              required: true
        - name: mobileImage
          label: 'Imagem para Mobile'
          description: 'Imagens do Banner para dispositivos Mobile'
          type: object
          fields:
            - name: src
              label: 'Selecione a imagem'
              description: 'Tamanho recomendado 750x1000 em .jpg, .jpeg, .webp ou .avif'
              type: image
              required: true
              options:
                media: banners
            - name: alt
              label: 'Descrição da Imagem para Mobile'
              description: 'Forneça um texto alternativo que descreva o conteúdo da imagem'
              type: string
              required: true      