content:
  - name: announcementBar
    label: 'Barra de anúncio'
    type: file
    path: 'src/cms/announcement-bar.json'
    format: 'json'
    fields: 
      - name: announcementBar
        label: 'Barra de anúncio'
        list: true
        type: string
  - name: generalConfiguration
    label: 'Configuração Geral'
    type: file
    path: 'src/cms/general-configuration.json'
    format: 'json'
    fields: 
      - name: text
        label: 'texto simples'
        type: string
      